import turtle
myturtle=turtle.Turtle()
myturtle.color('red')
myturtle.shape("turtle")
myturtle.begin_fill()
myturtle.forward(400)
myturtle.right(144)
myturtle.forward(400)
myturtle.right(144)
myturtle.forward(400)
myturtle.right(144)
myturtle.forward(400)
myturtle.right(144)
myturtle.forward(400)
myturtle.right(144)
myturtle.end_fill()
turtle.mainloop()